version: "2.1"
services:

  postgresdb:
    image: postgres:15.2-alpine
    ports:
      - "5438:5438"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - back
    command: -p 5438
    volumes:
      - app-volume-develop:/var/lib/postgresql/data

networks:
  back:
    driver: bridge
    
volumes:
  app-volume-develop: #
